#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
if [ -d .venv ]; then
  . .venv/bin/activate
fi

export STAR_PULSE_NETCONF_INTEGRATION_ENABLED="${STAR_PULSE_NETCONF_INTEGRATION_ENABLED:-true}"
export STAR_PULSE_NETCONF_TEST_HOST="${STAR_PULSE_NETCONF_TEST_HOST:-172.16.5.38}"
export STAR_PULSE_NETCONF_TEST_PORT="${STAR_PULSE_NETCONF_TEST_PORT:-830}"
export STAR_PULSE_NETCONF_TEST_USERNAME="${STAR_PULSE_NETCONF_TEST_USERNAME:-netconf}"
export STAR_PULSE_NETCONF_TEST_PASSWORD="${STAR_PULSE_NETCONF_TEST_PASSWORD:-netconf}"

pytest
